"""initial schema

Revision ID: a7f7fe700d8c
Revises: 
Create Date: 2026-02-22 21:38:05.569395
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7f7fe700d8c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('framework', sa.String(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('health_endpoint', sa.String(), nullable=True),
    sa.Column('tools', sa.JSON(), nullable=False),
    sa.Column('channels', sa.JSON(), nullable=False),
    sa.Column('maturity', sa.String(), nullable=False),
    sa.Column('cost_mode', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_health_check', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('agent_id')
    )
    op.create_table('envelope_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('envelope_id', sa.String(), nullable=False),
    sa.Column('trace_id', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('envelope_data', sa.JSON(), nullable=False),
    sa.Column('matched_rule_id', sa.String(), nullable=True),
    sa.Column('matched_rule_name', sa.String(), nullable=True),
    sa.Column('target_agent_id', sa.String(), nullable=True),
    sa.Column('dispatch_status', sa.String(), nullable=False),
    sa.Column('dispatch_result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_envelope_log_envelope_id'), 'envelope_log', ['envelope_id'], unique=False)
    op.create_index(op.f('ix_envelope_log_trace_id'), 'envelope_log', ['trace_id'], unique=False)
    op.create_table('rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('actions', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rules')
    op.drop_index(op.f('ix_envelope_log_trace_id'), table_name='envelope_log')
    op.drop_index(op.f('ix_envelope_log_envelope_id'), table_name='envelope_log')
    op.drop_table('envelope_log')
    op.drop_table('agents')
    # ### end Alembic commands ###
