"""Email output adapter — sends HTML emails from dispatch results via SMTP."""

import asyncio
import logging
import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

logger = logging.getLogger("trellis.outputs.email")


def _extract_priority(dispatch_result: dict) -> str | None:
    """Extract priority from dispatch result, checking multiple paths."""
    result = dispatch_result.get("result") or {}
    inner = result.get("result") or {}
    data = inner.get("data") or {}
    advisory = data.get("advisory") or {}

    # security triage path: result.result.data.advisory.risk_score.priority
    if priority := (advisory.get("risk_score") or {}).get("priority"):
        return priority
    # generic path: result.result.data.priority
    if priority := data.get("priority"):
        return priority
    return None


def _build_security_html(result: dict, priority: str) -> tuple[str, str]:
    """Build subject + HTML body for security advisory results."""
    inner = (result.get("result") or {}).get("result") or {}
    data = inner.get("data") or {}
    advisory = data.get("advisory") or {}

    cve_id = advisory.get("cve_id", "N/A")
    title = advisory.get("title", "Security Advisory")
    risk = advisory.get("risk_score") or {}
    score = risk.get("composite_score", "?")
    exec_summary = advisory.get("executive_summary", inner.get("text", ""))

    priority_emoji = {"CRITICAL": "🚨", "HIGH": "🔴", "MEDIUM": "🟡", "LOW": "🟢"}.get(priority, "⚠️")
    subject = f"[Trellis] {priority_emoji} {priority}: {title} ({cve_id})"

    affected = advisory.get("affected_systems") or []
    affected_rows = "".join(
        f"<tr><td>{s.get('system','')}</td><td>{s.get('category','')}</td>"
        f"<td>{s.get('criticality','')}</td></tr>"
        for s in affected
    ) or "<tr><td colspan='3'><em>No direct match in known tech stack</em></td></tr>"

    actions = advisory.get("recommended_actions") or []
    action_items = "".join(f"<li>{a}</li>" for a in actions) or "<li>Review and assess exposure</li>"

    escalation = advisory.get("escalation_path") or []
    escalation_items = "".join(f"<li>{e}</li>" for e in escalation)

    timeline = advisory.get("remediation_timeline", "")
    generated_at = advisory.get("generated_at", "")

    html = f"""<!DOCTYPE html>
<html>
<head>
  <style>
    body {{ font-family: -apple-system, Arial, sans-serif; color: #1a1a2e; max-width: 700px; margin: 0 auto; padding: 20px; }}
    .header {{ background: {'#dc2626' if priority == 'CRITICAL' else '#ea580c' if priority == 'HIGH' else '#ca8a04'}; color: white; padding: 20px; border-radius: 8px 8px 0 0; }}
    .header h1 {{ margin: 0; font-size: 18px; }}
    .header .meta {{ opacity: 0.9; font-size: 13px; margin-top: 6px; }}
    .body {{ border: 1px solid #e2e8f0; border-top: none; padding: 20px; border-radius: 0 0 8px 8px; }}
    .score-badge {{ display: inline-block; background: {'#dc2626' if priority == 'CRITICAL' else '#ea580c'}; color: white; padding: 4px 10px; border-radius: 4px; font-weight: bold; font-size: 14px; }}
    table {{ width: 100%; border-collapse: collapse; margin: 10px 0; }}
    th {{ background: #f1f5f9; text-align: left; padding: 8px; font-size: 13px; }}
    td {{ padding: 8px; border-top: 1px solid #e2e8f0; font-size: 13px; }}
    h3 {{ color: #475569; font-size: 14px; margin: 20px 0 8px; text-transform: uppercase; letter-spacing: 0.05em; }}
    ul {{ margin: 4px 0; padding-left: 20px; font-size: 14px; }}
    li {{ margin: 4px 0; }}
    .footer {{ margin-top: 20px; padding-top: 16px; border-top: 1px solid #e2e8f0; font-size: 12px; color: #94a3b8; }}
  </style>
</head>
<body>
  <div class="header">
    <h1>🔒 {title}</h1>
    <div class="meta">{cve_id} &nbsp;|&nbsp; Risk Score: {score}/100 &nbsp;|&nbsp; <span class="score-badge">{priority}</span></div>
  </div>
  <div class="body">
    <h3>Executive Summary</h3>
    <p style="font-size:14px">{exec_summary}</p>

    <h3>Affected Systems</h3>
    <table>
      <tr><th>System</th><th>Category</th><th>Criticality</th></tr>
      {affected_rows}
    </table>

    <h3>Recommended Actions</h3>
    <ul>{action_items}</ul>

    <h3>Escalation Path</h3>
    <ul>{escalation_items}</ul>

    {'<h3>Remediation Timeline</h3><p style="font-size:14px">' + timeline + '</p>' if timeline else ''}

    <div class="footer">
      Generated by Trellis Security Agent &nbsp;|&nbsp; {generated_at}
    </div>
  </div>
</body>
</html>"""

    return subject, html


def _build_generic_html(result: dict, priority: str | None) -> tuple[str, str]:
    """Build subject + HTML body for generic (non-security) results."""
    agent = result.get("target_agent", "agent")
    rule = result.get("matched_rule", "")
    inner = (result.get("result") or {}).get("result") or {}
    text = inner.get("text", "No summary available.")

    label = f" [{priority}]" if priority else ""
    subject = f"[Trellis]{label} Result from {agent}"
    html = f"""<!DOCTYPE html>
<html>
<body style="font-family:Arial,sans-serif;color:#1a1a2e;max-width:600px;margin:0 auto;padding:20px">
  <h2 style="color:#1e40af">Trellis Dispatch Result</h2>
  <p><strong>Agent:</strong> {agent}<br><strong>Rule:</strong> {rule}{f'<br><strong>Priority:</strong> {priority}' if priority else ''}</p>
  <hr>
  <pre style="background:#f8fafc;padding:16px;border-radius:6px;white-space:pre-wrap;font-size:13px">{text}</pre>
  <p style="color:#94a3b8;font-size:12px">Sent by Trellis output adapter.</p>
</body>
</html>"""
    return subject, html


def _send_smtp(to: str, subject: str, html: str) -> None:
    """Synchronous SMTP send — runs in thread pool."""
    host = os.environ.get("TRELLIS_SMTP_HOST", "smtp.gmail.com")
    port = int(os.environ.get("TRELLIS_SMTP_PORT", "587"))
    user = os.environ.get("TRELLIS_SMTP_USER", "")
    password = os.environ.get("TRELLIS_SMTP_PASSWORD", "")
    from_addr = os.environ.get("TRELLIS_SMTP_FROM", user)

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = from_addr
    msg["To"] = to
    msg.attach(MIMEText(html, "html"))

    with smtplib.SMTP(host, port) as smtp:
        smtp.ehlo()
        smtp.starttls()
        if user and password:
            smtp.login(user, password)
        smtp.sendmail(from_addr, [to], msg.as_string())


async def send_email_output(dispatch_result: dict, output_config: dict) -> None:
    """Send email for a dispatch result. Non-blocking — errors are logged, not raised."""
    to = output_config.get("to")
    if not to:
        logger.warning("email output: missing 'to' address in config")
        return

    try:
        priority = _extract_priority(dispatch_result)
        agent = dispatch_result.get("target_agent", "")

        # Use structured security template if this is from a security agent
        if "security" in agent:
            subject, html = _build_security_html(dispatch_result, priority or "UNKNOWN")
        else:
            subject, html = _build_generic_html(dispatch_result, priority)

        loop = asyncio.get_event_loop()
        await loop.run_in_executor(None, _send_smtp, to, subject, html)
        logger.info(f"Email sent to {to}: {subject}")
    except Exception as e:
        logger.warning(f"Email output failed (non-fatal): {e}")
